# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/FanConstraints.xdc

# Block Designs: bd/mainBlock/mainBlock.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlock || ORIG_REF_NAME==mainBlock} -quiet] -quiet

# XDC: bd/mainBlock/mainBlock_ooc.xdc
